2020-02-17 18:37:39,903 	 [INFO | run_locally.py : line 30] >> Pipeline start
2020-02-17 18:37:39,903 	 [INFO | run_locally.py : line 38] >> The run mode is:run_bau
2020-02-17 18:37:39,923 	 [ERROR | dataimport.py : line 68] >> site=90515 | Unable download data. Check log
2020-02-17 18:37:39,927 	 [INFO | dataimport.py : line 37] >> site=90515 | utils/configuration_failed_files.csv is generated
2020-02-17 18:37:39,930 	 [WARNING | dataimport.py : line 77] >> site=90515 | No data is downloaded
2020-02-17 18:37:39,937 	 [ERROR | dataimport.py : line 68] >> site=03805_PRV | Unable download data. Check log
2020-02-17 18:37:39,941 	 [INFO | dataimport.py : line 37] >> site=03805_PRV | utils/configuration_failed_files.csv is generated
2020-02-17 18:37:39,942 	 [WARNING | dataimport.py : line 77] >> site=03805_PRV | No data is downloaded
2020-02-17 18:37:39,943 	 [INFO | run_locally.py : line 65] >> Pipeline end
